name: version sync

on:
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  version_sync:
    runs-on: macos-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.SECRET_GITHUB_TOKEN }}

      - name: Calculate new version
        run: |
          version=$(grep 'version:' pubspec.yaml | awk '{print $2}')
          echo "Current version: $version"
          IFS='+' read -r base_version build_number <<< "$version"
          build_number=$((build_number + 1))
          new_version="${base_version}+${build_number}"
          echo "New version: $new_version"
          echo "NEW_VERSION=$new_version" >> $GITHUB_ENV
          
      - name: git config
        run: |
          git config --global user.name '6cessfuldev'
          git config --global user.email '6cessfuldev@gmail.com'

      - name: Checkout main Branch
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.SECRET_GITHUB_TOKEN }}

      - name: pubspec 수정 및 커밋 푸쉬
        run: |
          sed -i '' "s/version: .*/version: $new_version/" pubspec.yaml
          git add pubspec.yaml
          git commit -m "빌드 넘버 업데이트 to $new_version"
          git push origin main

      - name: Checkout develop Branch
        uses: actions/checkout@v3
        with:
          ref: develop
          token: ${{ secrets.SECRET_GITHUB_TOKEN }}
        
      - name: pubspec 수정 및 커밋 푸쉬
        run: |
          sed -i '' "s/version: .*/version: $new_version/" pubspec.yaml
          git add pubspec.yaml
          git commit -m "빌드 넘버 업데이트 to $new_version"
          git push origin develop
